[package]
name = "ghost"
version = "0.10.0"
description = "A minimalist markdown editor"
authors = ["you"]
edition = "2021"

[lib]
name = "ghost_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
tauri-plugin-store = "2"
tauri-plugin-clipboard-manager = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
pulldown-cmark = "0.12"
notify = "7"
notify-debouncer-mini = "0.5"
font-kit = "0.14"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
trash = "5"
memchr = "2"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "3.7"
security-framework-sys = "2.17"
objc2 = "0.6"
objc2-foundation = "0.3"
objc2-app-kit = { version = "0.3", features = ["NSView", "NSMenu", "NSMenuItem", "NSEvent", "NSResponder", "NSPasteboard", "NSImage", "NSImageRep", "NSBitmapImageRep", "NSApplication", "NSRunningApplication", "NSWindow", "NSButton", "NSControl", "NSWorkspace"] }
objc2-image-io = { version = "0.3.2", features = ["CGImageSource"] }
objc2-core-graphics = { version = "0.3.2", features = ["CGImage"] }
objc2-core-foundation = "0.3.2"
objc2-pdf-kit = "0.3.2"
objc2-quick-look-ui = { version = "0.3.2", default-features = false, features = ["QLPreviewItem", "QLPreviewView", "objc2-app-kit"] }

[target."cfg(unix)".dependencies]
xattr = "1.6.1"
