-- Automatic, user-restorable Cloud document versions. The append-only Yjs
-- update log remains the collaborative source of truth; versions are durable
-- recovery points with a human-readable Markdown representation.

create table if not exists public.cloud_document_versions (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.cloud_documents(document_id) on delete cascade,
  author_id uuid references auth.users(id) on delete set null,
  reason text not null check (reason in ('automatic', 'restore', 'restore_backup')),
  restored_from_version_id bigint references public.cloud_document_versions(id) on delete set null,
  markdown_snapshot text not null check (octet_length(markdown_snapshot) <= 5242880),
  yjs_snapshot text not null check (
    yjs_snapshot ~ '^[A-Za-z0-9+/]*={0,2}$'
    and octet_length(decode(yjs_snapshot, 'base64')) <= 10485760
  ),
  created_at timestamptz not null default now()
);

create index if not exists cloud_document_versions_document_created
on public.cloud_document_versions (document_id, created_at desc, id desc);

drop function if exists public.cloud_create_document_version(uuid, text, text, text, bigint);
create function public.cloud_create_document_version(
  target_document_id uuid,
  snapshot_markdown text,
  snapshot_yjs text,
  version_reason text default 'automatic',
  target_restored_from_version_id bigint default null
)
returns public.cloud_document_versions
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  latest public.cloud_document_versions;
  result public.cloud_document_versions;
begin
  if current_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if not private.cloud_has_role(target_document_id, 2, current_user_id) then
    raise exception 'Cloud document is not editable' using errcode = '42501';
  end if;
  if version_reason not in ('automatic', 'restore', 'restore_backup') then
    raise exception 'Unsupported document version reason';
  end if;
  if octet_length(snapshot_markdown) > 5242880 then
    raise exception 'Markdown snapshot is too large';
  end if;
  if snapshot_yjs !~ '^[A-Za-z0-9+/]*={0,2}$'
    or octet_length(decode(snapshot_yjs, 'base64')) > 10485760 then
    raise exception 'Yjs snapshot is invalid or too large';
  end if;
  if target_restored_from_version_id is not null and not exists (
    select 1
    from public.cloud_document_versions as version
    where version.id = target_restored_from_version_id
      and version.document_id = target_document_id
  ) then
    raise exception 'Restored version does not belong to this document';
  end if;

  -- Serialize checkpoints for one document so simultaneous clients do not
  -- create duplicate versions for the same converged content.
  perform pg_advisory_xact_lock(hashtext(target_document_id::text));
  select version.* into latest
  from public.cloud_document_versions as version
  where version.document_id = target_document_id
  order by version.created_at desc, version.id desc
  limit 1;

  if latest.id is not null then
    if latest.markdown_snapshot = snapshot_markdown then
      return latest;
    end if;
    if version_reason = 'automatic'
      and latest.created_at > now() - interval '5 minutes' then
      return latest;
    end if;
  end if;

  insert into public.cloud_document_versions (
    document_id,
    author_id,
    reason,
    restored_from_version_id,
    markdown_snapshot,
    yjs_snapshot
  ) values (
    target_document_id,
    current_user_id,
    version_reason,
    target_restored_from_version_id,
    snapshot_markdown,
    snapshot_yjs
  ) returning * into result;

  update public.cloud_documents
  set markdown_snapshot = snapshot_markdown,
      snapshot_updated_at = result.created_at,
      updated_at = result.created_at
  where document_id = target_document_id;

  return result;
end
$$;

alter table public.cloud_document_versions enable row level security;
revoke all on public.cloud_document_versions from anon, authenticated;
grant select on public.cloud_document_versions to authenticated;

revoke all on function public.cloud_create_document_version(uuid, text, text, text, bigint)
from public, anon;
grant execute on function public.cloud_create_document_version(uuid, text, text, text, bigint)
to authenticated;

drop policy if exists "cloud users can read document versions" on public.cloud_document_versions;
create policy "cloud users can read document versions"
on public.cloud_document_versions for select to authenticated
using (private.cloud_has_role(document_id, 1, (select auth.uid())));
