-- Retained Ghost Cloud control plane. The Phase 0 collaboration_spike_* tables
-- remain disposable and are not referenced by production clients.

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists public.cloud_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cloud_workspaces (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null unique references auth.users(id) on delete cascade,
  name text not null default 'My Cloud' check (char_length(name) between 1 and 120),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cloud_items (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.cloud_workspaces(id) on delete cascade,
  parent_id uuid references public.cloud_items(id) on delete cascade,
  kind text not null check (kind in ('folder', 'document')),
  name text not null check (
    char_length(name) between 1 and 255
    and name = btrim(name)
    and position('/' in name) = 0
  ),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create unique index if not exists cloud_items_unique_live_sibling
on public.cloud_items (
  workspace_id,
  coalesce(parent_id, '00000000-0000-0000-0000-000000000000'::uuid),
  lower(name)
)
where deleted_at is null;

create index if not exists cloud_items_parent_order
on public.cloud_items (workspace_id, parent_id, kind, lower(name))
where deleted_at is null;

create table if not exists public.cloud_memberships (
  item_id uuid not null references public.cloud_items(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('owner', 'editor', 'viewer')),
  granted_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  primary key (item_id, user_id)
);

create index if not exists cloud_memberships_user_items
on public.cloud_memberships (user_id, item_id);

create table if not exists public.cloud_documents (
  document_id uuid primary key references public.cloud_items(id) on delete cascade,
  schema_version integer not null default 1 check (schema_version > 0),
  markdown_snapshot text not null default '',
  snapshot_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cloud_document_updates (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.cloud_documents(document_id) on delete cascade,
  author_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  client_id uuid not null,
  client_sequence bigint not null check (client_sequence > 0),
  update text not null check (
    update ~ '^[A-Za-z0-9+/]*={0,2}$'
    and octet_length(decode(update, 'base64')) <= 1048576
  ),
  created_at timestamptz not null default now(),
  unique (document_id, client_id, client_sequence)
);

create index if not exists cloud_document_updates_document_order
on public.cloud_document_updates (document_id, id);

create or replace function private.cloud_role_rank(role_name text)
returns integer
language sql
immutable
set search_path = ''
as $$
  select case role_name
    when 'owner' then 3
    when 'editor' then 2
    when 'viewer' then 1
    else 0
  end
$$;

create or replace function private.cloud_effective_role(
  target_item_id uuid,
  target_user_id uuid
)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  with recursive ancestors as (
    select item.id, item.parent_id, item.workspace_id
    from public.cloud_items as item
    where item.id = target_item_id and item.deleted_at is null

    union

    select parent.id, parent.parent_id, parent.workspace_id
    from public.cloud_items as parent
    join ancestors on ancestors.parent_id = parent.id
    where parent.deleted_at is null
  ), candidate_roles as (
    select 'owner'::text as role
    from ancestors
    join public.cloud_workspaces as workspace on workspace.id = ancestors.workspace_id
    where workspace.owner_id = target_user_id

    union all

    select membership.role
    from ancestors
    join public.cloud_memberships as membership on membership.item_id = ancestors.id
    where membership.user_id = target_user_id
  )
  select role
  from candidate_roles
  order by private.cloud_role_rank(role) desc
  limit 1
$$;

create or replace function private.cloud_has_role(
  target_item_id uuid,
  minimum_rank integer,
  target_user_id uuid default auth.uid()
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select target_user_id is not null
    and private.cloud_role_rank(
      private.cloud_effective_role(target_item_id, target_user_id)
    ) >= minimum_rank
$$;

create or replace function private.cloud_topic_document_id(topic_name text)
returns uuid
language sql
immutable
set search_path = ''
as $$
  select case
    when topic_name ~ '^ghost-cloud:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
      then substring(topic_name from 13)::uuid
    else null
  end
$$;

create or replace function public.cloud_ensure_workspace()
returns public.cloud_workspaces
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  result public.cloud_workspaces;
begin
  if current_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) then
    raise exception 'A permanent account is required' using errcode = '42501';
  end if;

  insert into public.cloud_profiles (id, email)
  select current_user_id, auth.jwt() ->> 'email'
  on conflict (id) do update
  set email = excluded.email, updated_at = now();

  insert into public.cloud_workspaces (owner_id)
  values (current_user_id)
  on conflict (owner_id) do nothing;

  select workspace.* into result
  from public.cloud_workspaces as workspace
  where workspace.owner_id = current_user_id;
  return result;
end
$$;

create or replace function public.cloud_create_item(
  item_kind text,
  item_name text,
  target_parent_id uuid default null
)
returns public.cloud_items
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  target_workspace public.cloud_workspaces;
  normalized_name text := btrim(item_name);
  result public.cloud_items;
begin
  if current_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if item_kind not in ('folder', 'document') then
    raise exception 'Unsupported Cloud item type';
  end if;
  if normalized_name = '' or char_length(normalized_name) > 255
    or position('/' in normalized_name) > 0 then
    raise exception 'Invalid Cloud item name';
  end if;
  if item_kind = 'document' and lower(normalized_name) not like '%.md' then
    normalized_name := normalized_name || '.md';
  end if;

  if target_parent_id is null then
    select workspace.* into target_workspace
    from public.cloud_workspaces as workspace
    where workspace.owner_id = current_user_id;
    if target_workspace.id is null then
      raise exception 'Cloud workspace not found';
    end if;
  else
    select workspace.* into target_workspace
    from public.cloud_items as parent
    join public.cloud_workspaces as workspace on workspace.id = parent.workspace_id
    where parent.id = target_parent_id
      and parent.kind = 'folder'
      and parent.deleted_at is null;
    if target_workspace.id is null
      or not private.cloud_has_role(target_parent_id, 2, current_user_id) then
      raise exception 'Cloud parent is not editable' using errcode = '42501';
    end if;
  end if;

  insert into public.cloud_items (
    workspace_id, parent_id, kind, name, created_by
  ) values (
    target_workspace.id, target_parent_id, item_kind, normalized_name, current_user_id
  ) returning * into result;

  if item_kind = 'document' then
    insert into public.cloud_documents (document_id) values (result.id);
  end if;
  return result;
exception
  when unique_violation then
    raise exception 'A Cloud item with that name already exists' using errcode = '23505';
end
$$;

create or replace function public.cloud_rename_item(
  target_item_id uuid,
  item_name text
)
returns public.cloud_items
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_name text := btrim(item_name);
  existing_kind text;
  result public.cloud_items;
begin
  if not private.cloud_has_role(target_item_id, 2, auth.uid()) then
    raise exception 'Cloud item is not editable' using errcode = '42501';
  end if;
  select kind into existing_kind from public.cloud_items where id = target_item_id;
  if normalized_name = '' or char_length(normalized_name) > 255
    or position('/' in normalized_name) > 0 then
    raise exception 'Invalid Cloud item name';
  end if;
  if existing_kind = 'document' and lower(normalized_name) not like '%.md' then
    normalized_name := normalized_name || '.md';
  end if;
  update public.cloud_items
  set name = normalized_name, updated_at = now()
  where id = target_item_id and deleted_at is null
  returning * into result;
  return result;
exception
  when unique_violation then
    raise exception 'A Cloud item with that name already exists' using errcode = '23505';
end
$$;

create or replace function public.cloud_document_role(target_document_id uuid)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select private.cloud_effective_role(target_document_id, auth.uid())
$$;

create or replace function private.handle_cloud_user_created()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not coalesce(new.is_anonymous, false) then
    insert into public.cloud_profiles (id, email)
    values (new.id, new.email)
    on conflict (id) do update set email = excluded.email, updated_at = now();
    insert into public.cloud_workspaces (owner_id)
    values (new.id)
    on conflict (owner_id) do nothing;
  end if;
  return new;
end
$$;

drop trigger if exists on_auth_user_created_create_cloud on auth.users;
create trigger on_auth_user_created_create_cloud
after insert or update of is_anonymous, email on auth.users
for each row execute function private.handle_cloud_user_created();

alter table public.cloud_profiles enable row level security;
alter table public.cloud_workspaces enable row level security;
alter table public.cloud_items enable row level security;
alter table public.cloud_memberships enable row level security;
alter table public.cloud_documents enable row level security;
alter table public.cloud_document_updates enable row level security;

revoke all on public.cloud_profiles from anon, authenticated;
revoke all on public.cloud_workspaces from anon, authenticated;
revoke all on public.cloud_items from anon, authenticated;
revoke all on public.cloud_memberships from anon, authenticated;
revoke all on public.cloud_documents from anon, authenticated;
revoke all on public.cloud_document_updates from anon, authenticated;

grant select on public.cloud_profiles to authenticated;
grant select on public.cloud_workspaces to authenticated;
grant select on public.cloud_items to authenticated;
grant select on public.cloud_memberships to authenticated;
grant select on public.cloud_documents to authenticated;
grant select, insert on public.cloud_document_updates to authenticated;
grant usage, select on sequence public.cloud_document_updates_id_seq to authenticated;

revoke all on function public.cloud_ensure_workspace() from public, anon;
revoke all on function public.cloud_create_item(text, text, uuid) from public, anon;
revoke all on function public.cloud_rename_item(uuid, text) from public, anon;
revoke all on function public.cloud_document_role(uuid) from public, anon;
grant execute on function public.cloud_ensure_workspace() to authenticated;
grant execute on function public.cloud_create_item(text, text, uuid) to authenticated;
grant execute on function public.cloud_rename_item(uuid, text) to authenticated;
grant execute on function public.cloud_document_role(uuid) to authenticated;

drop policy if exists "cloud users can read their profile" on public.cloud_profiles;
create policy "cloud users can read their profile"
on public.cloud_profiles for select to authenticated
using ((select auth.uid()) = id);

drop policy if exists "cloud users can read visible workspaces" on public.cloud_workspaces;
create policy "cloud users can read visible workspaces"
on public.cloud_workspaces for select to authenticated
using (
  owner_id = (select auth.uid())
  or exists (
    select 1 from public.cloud_items as item
    where item.workspace_id = cloud_workspaces.id
      and private.cloud_has_role(item.id, 1, (select auth.uid()))
  )
);

drop policy if exists "cloud users can read visible items" on public.cloud_items;
create policy "cloud users can read visible items"
on public.cloud_items for select to authenticated
using (
  deleted_at is null
  and private.cloud_has_role(id, 1, (select auth.uid()))
);

drop policy if exists "cloud users can read relevant memberships" on public.cloud_memberships;
create policy "cloud users can read relevant memberships"
on public.cloud_memberships for select to authenticated
using (
  user_id = (select auth.uid())
  or private.cloud_has_role(item_id, 3, (select auth.uid()))
);

drop policy if exists "cloud users can read visible documents" on public.cloud_documents;
create policy "cloud users can read visible documents"
on public.cloud_documents for select to authenticated
using (private.cloud_has_role(document_id, 1, (select auth.uid())));

drop policy if exists "cloud users can load visible updates" on public.cloud_document_updates;
create policy "cloud users can load visible updates"
on public.cloud_document_updates for select to authenticated
using (private.cloud_has_role(document_id, 1, (select auth.uid())));

drop policy if exists "cloud editors can append updates" on public.cloud_document_updates;
create policy "cloud editors can append updates"
on public.cloud_document_updates for insert to authenticated
with check (
  author_id = (select auth.uid())
  and private.cloud_has_role(document_id, 2, (select auth.uid()))
);

drop policy if exists "cloud members can receive realtime" on realtime.messages;
create policy "cloud members can receive realtime"
on realtime.messages for select to authenticated
using (
  realtime.messages.extension = 'broadcast'
  and private.cloud_has_role(
    private.cloud_topic_document_id((select realtime.topic())),
    1,
    (select auth.uid())
  )
);

drop policy if exists "cloud editors can send realtime" on realtime.messages;
create policy "cloud editors can send realtime"
on realtime.messages for insert to authenticated
with check (
  realtime.messages.extension = 'broadcast'
  and private.cloud_has_role(
    private.cloud_topic_document_id((select realtime.topic())),
    2,
    (select auth.uid())
  )
);
