-- Disposable Phase 0 schema. This is intentionally smaller than the future
-- Cloud product schema and should not be promoted unchanged to production.

create table if not exists public.collaboration_spike_documents (
  id uuid primary key,
  title text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.collaboration_spike_members (
  room_id uuid not null references public.collaboration_spike_documents(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('editor', 'viewer')),
  created_at timestamptz not null default now(),
  primary key (room_id, user_id)
);

create table if not exists public.collaboration_spike_updates (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.collaboration_spike_documents(id) on delete cascade,
  author_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  client_id uuid not null,
  client_sequence bigint not null check (client_sequence > 0),
  update text not null check (
    update ~ '^[A-Za-z0-9+/]*={0,2}$'
    and octet_length(decode(update, 'base64')) <= 1048576
  ),
  created_at timestamptz not null default now(),
  unique (room_id, client_id, client_sequence)
);

create index if not exists collaboration_spike_updates_room_order
  on public.collaboration_spike_updates(room_id, id);

insert into public.collaboration_spike_documents (id, title)
values ('00000000-0000-4000-8000-000000000001', 'Ghost multiplayer spike')
on conflict (id) do nothing;

alter table public.collaboration_spike_documents enable row level security;
alter table public.collaboration_spike_members enable row level security;
alter table public.collaboration_spike_updates enable row level security;

revoke all on public.collaboration_spike_documents from anon, authenticated;
revoke all on public.collaboration_spike_members from anon, authenticated;
revoke all on public.collaboration_spike_updates from anon, authenticated;

grant select on public.collaboration_spike_documents to authenticated;
grant select on public.collaboration_spike_members to authenticated;
grant select, insert on public.collaboration_spike_updates to authenticated;
grant usage, select on sequence public.collaboration_spike_updates_id_seq to authenticated;

drop policy if exists "spike members can read their room" on public.collaboration_spike_documents;
create policy "spike members can read their room"
on public.collaboration_spike_documents
for select
to authenticated
using (
  exists (
    select 1
    from public.collaboration_spike_members member
    where member.room_id = collaboration_spike_documents.id
      and member.user_id = (select auth.uid())
  )
);

drop policy if exists "spike users can read their membership" on public.collaboration_spike_members;
create policy "spike users can read their membership"
on public.collaboration_spike_members
for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "spike members can load updates" on public.collaboration_spike_updates;
create policy "spike members can load updates"
on public.collaboration_spike_updates
for select
to authenticated
using (
  exists (
    select 1
    from public.collaboration_spike_members member
    where member.room_id = collaboration_spike_updates.room_id
      and member.user_id = (select auth.uid())
  )
);

drop policy if exists "spike editors can append updates" on public.collaboration_spike_updates;
create policy "spike editors can append updates"
on public.collaboration_spike_updates
for insert
to authenticated
with check (
  author_id = (select auth.uid())
  and exists (
    select 1
    from public.collaboration_spike_members member
    where member.room_id = collaboration_spike_updates.room_id
      and member.user_id = (select auth.uid())
      and member.role = 'editor'
  )
);

-- Realtime Authorization is evaluated when a private channel is joined. A
-- viewer gets broadcast read permission but no broadcast write permission.
drop policy if exists "spike members can receive realtime" on realtime.messages;
create policy "spike members can receive realtime"
on realtime.messages
for select
to authenticated
using (
  realtime.messages.extension = 'broadcast'
  and exists (
    select 1
    from public.collaboration_spike_members member
    where member.user_id = (select auth.uid())
      and (select realtime.topic()) = 'ghost-spike:' || member.room_id::text
  )
);

drop policy if exists "spike editors can send realtime" on realtime.messages;
create policy "spike editors can send realtime"
on realtime.messages
for insert
to authenticated
with check (
  realtime.messages.extension = 'broadcast'
  and exists (
    select 1
    from public.collaboration_spike_members member
    where member.user_id = (select auth.uid())
      and member.role = 'editor'
      and (select realtime.topic()) = 'ghost-spike:' || member.room_id::text
  )
);
